workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    environment:
      vars:
        APP_STORE_CONNECT_ISSUER_ID: ""
        APP_STORE_CONNECT_KEY_IDENTIFIER: ""
        APP_STORE_CONNECT_PRIVATE_KEY: ""
        CERTIFICATE_PRIVATE_KEY: ""
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Install CocoaPods
        script: cd ios && pod install && cd ..
      - name: Flutter build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/*.app
      - build/**/outputs/**/*.apk
      - flutter_drive.log

  android-release:
    name: Android Release Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Flutter build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
